/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package intellibook;

import Models.Prestamo;
import Models.PrestamoDAO;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JULI4
 */
public class Page_prestamo extends javax.swing.JPanel {

    /**
     * Creates new form Page_prestamo
     */
    public Page_prestamo() {
        initComponents();
    }

    
    //Metodo para limpiar
    public void limpiar(){
        txt_buscar.setText("");
        txt_fechaEntrega.setText("");
        txt_idLibro.setText("");
        txt_unidades.setText("");
        txt_numerocontrolPrestamo.setText("");
        txt_IDPrestamo.setText("");
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Prestamo_Panel = new javax.swing.JPanel();
        Prestamo_Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_Informacion_Prestamo = new javax.swing.JPanel();
        label_numeroControl = new javax.swing.JLabel();
        label_fechaEntrega = new javax.swing.JLabel();
        label_unidades = new javax.swing.JLabel();
        txt_numerocontrolPrestamo = new javax.swing.JTextField();
        txt_fechaEntrega = new javax.swing.JTextField();
        txt_buscar = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        label_libro = new javax.swing.JLabel();
        txt_unidades = new javax.swing.JTextField();
        lb_nombre1 = new javax.swing.JLabel();
        label_buscarNumero = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_prestamos = new javax.swing.JTable();
        txt_idLibro = new javax.swing.JTextField();
        label_id = new javax.swing.JLabel();
        txt_IDPrestamo = new javax.swing.JTextField();

        Prestamo_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Prestamo_Titulo.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prestamo");

        javax.swing.GroupLayout Prestamo_TituloLayout = new javax.swing.GroupLayout(Prestamo_Titulo);
        Prestamo_Titulo.setLayout(Prestamo_TituloLayout);
        Prestamo_TituloLayout.setHorizontalGroup(
            Prestamo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Prestamo_TituloLayout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        Prestamo_TituloLayout.setVerticalGroup(
            Prestamo_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Prestamo_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Prestamo_Panel.add(Prestamo_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Panel_Informacion_Prestamo.setBackground(new java.awt.Color(51, 102, 255));

        label_numeroControl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_numeroControl.setText("Numero de control:");

        label_fechaEntrega.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_fechaEntrega.setText("Fecha de entrega:");

        label_unidades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_unidades.setText("Unidades:");

        txt_numerocontrolPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numerocontrolPrestamoActionPerformed(evt);
            }
        });

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        btn_registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_consultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        label_libro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_libro.setText("ID Libro");

        txt_unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unidadesActionPerformed(evt);
            }
        });

        lb_nombre1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nombre1.setText("Buscar");

        label_buscarNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_buscarNumero.setText("Numero de control:");

        tabla_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "N.Control", "Unidades", "ID Libro", "F. salida", "F. entrega"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_prestamos);

        txt_idLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idLibroActionPerformed(evt);
            }
        });

        label_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id.setText("ID:");

        txt_IDPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDPrestamoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_Informacion_PrestamoLayout = new javax.swing.GroupLayout(Panel_Informacion_Prestamo);
        Panel_Informacion_Prestamo.setLayout(Panel_Informacion_PrestamoLayout);
        Panel_Informacion_PrestamoLayout.setHorizontalGroup(
            Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                        .addComponent(btn_registrar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_consultar)
                        .addGap(34, 34, 34))
                    .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                        .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_numeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_numerocontrolPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                                .addGap(0, 53, Short.MAX_VALUE)
                                .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                                        .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(label_buscarNumero))
                                        .addGap(18, 18, 18)
                                        .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_IDPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(label_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(113, 113, 113))
                            .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addContainerGap())))))
        );
        Panel_Informacion_PrestamoLayout.setVerticalGroup(
            Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre1)
                    .addComponent(label_libro))
                .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_buscarNumero)
                            .addComponent(label_id))
                        .addGap(10, 10, 10)
                        .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscar)
                            .addComponent(txt_IDPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txt_idLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_numeroControl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_numerocontrolPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Informacion_PrestamoLayout.createSequentialGroup()
                        .addComponent(label_fechaEntrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_unidades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Panel_Informacion_PrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        Prestamo_Panel.add(Panel_Informacion_Prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Prestamo_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Prestamo_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_numerocontrolPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numerocontrolPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numerocontrolPrestamoActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void txt_unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unidadesActionPerformed

    private void txt_idLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idLibroActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
       
             // Obtener los valores de los campos de entrada
    String id_libro = txt_idLibro.getText();
    String numeroControl = txt_numerocontrolPrestamo.getText();
    String fechaEntregaText = txt_fechaEntrega.getText();
    String unidadesText = txt_unidades.getText();

    // Verificar si se ingresaron los datos requeridos
    if (id_libro.isEmpty() || numeroControl.isEmpty() || fechaEntregaText.isEmpty() || unidadesText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese todos los datos requeridos");
    } else {
        LocalDate fechaEntrega;
        try {
            // Parsear la fecha de entrega si el campo no está vacío
            fechaEntrega = LocalDate.parse(fechaEntregaText);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "El formato de fecha de entrega es incorrecto");
            return; // Salir del método en caso de error
        }

        int unidades;
        try {
            unidades = Integer.parseInt(unidadesText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor de unidades debe ser un número entero válido");
            return; // Salir del método en caso de error
        }

        // Crear un objeto Prestamo con los valores obtenidos
        Prestamo prestamo = new Prestamo();
        prestamo.setIdLibro(id_libro);
        prestamo.setNumeroControl(numeroControl);
        prestamo.setFechaEntrega(fechaEntrega);
        prestamo.setUnidades(unidades);

        // Crear una instancia de PrestamoDAO
        PrestamoDAO prestamoDAO = new PrestamoDAO();

        // Llamar al método registrar de PrestamoDAO
        if (prestamoDAO.registrar(prestamo)) {
            JOptionPane.showMessageDialog(null, "Préstamo registrado correctamente");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Error al registrar el préstamo");
        }
    }


        
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
          // CODIGO DEL BOTON DE CONSULTA 
        PrestamoDAO prestamodao = new PrestamoDAO();
        DefaultTableModel modelo = prestamodao.consultar();
        tabla_prestamos.setModel(modelo);
            
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // CODIGO BOTON ELIMINAR
            // Verificar si se ha ingresado el número de control y el ID del préstamo
    if (txt_IDPrestamo.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese el ID del préstamo");
        return;
    }

    // Obtener el ID del préstamo ingresado
    int idPrestamo = Integer.parseInt(txt_IDPrestamo.getText());

    // Crear una instancia de la clase PrestamoDAO
    PrestamoDAO prestamoDAO = new PrestamoDAO();

    // Eliminar el préstamo utilizando el ID del préstamo
    boolean eliminado = prestamoDAO.eliminar(idPrestamo);

    // Mostrar un mensaje de confirmación
    if (eliminado) {
        JOptionPane.showMessageDialog(null, "Préstamo eliminado correctamente");
    } else {
        JOptionPane.showMessageDialog(null, "No se pudo eliminar el préstamo");
    }

    // Limpiar el formulario después de eliminar el préstamo
    limpiar();

     
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
       //BOTON MODIFICAR
           // Obtener los datos ingresados por el usuario
    String idPrestamo = txt_IDPrestamo.getText();
    String idLibro = txt_idLibro.getText();
    String numeroControl = txt_numerocontrolPrestamo.getText();
    String fechaEntregaText = txt_fechaEntrega.getText();
    String unidadesText = txt_unidades.getText();

    // Verificar si se ingresaron los datos requeridos
    if (idPrestamo.isEmpty() || idLibro.isEmpty() || numeroControl.isEmpty() || fechaEntregaText.isEmpty() || unidadesText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese todos los datos requeridos");
    } else {
        // Parsear la fecha de entrega
        LocalDate fechaEntrega;
        try {
            fechaEntrega = LocalDate.parse(fechaEntregaText);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "El formato de fecha de entrega es incorrecto");
            return; // Salir del método en caso de error
        }

        // Verificar si se ingresó un valor numérico válido para unidades
        int unidades;
        try {
            unidades = Integer.parseInt(unidadesText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor de unidades debe ser un número entero válido");
            return; // Salir del método en caso de error
        }

        // Crear un objeto Prestamo con los datos ingresados
        Prestamo prestamo = new Prestamo();
        prestamo.setId(Integer.parseInt(idPrestamo));
        prestamo.setIdLibro(idLibro);
        prestamo.setNumeroControl(numeroControl);
        prestamo.setFechaEntrega(fechaEntrega);
        prestamo.setUnidades(unidades);

        // Instanciar la clase PrestamoDAO y llamar al método modificar
        PrestamoDAO prestamoDAO = new PrestamoDAO();
        boolean exito = prestamoDAO.modificar(prestamo);

        if (exito) {
            JOptionPane.showMessageDialog(null, "Préstamo modificado exitosamente");
            limpiar(); // Limpiar los campos después de la modificación
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo modificar el préstamo");
        }
    }
    
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // CODIGO BOTON BUSCAR
        // CODIGO DEL BOTON BUSCAR 
    
    String numeroControl = txt_buscar.getText();
    PrestamoDAO prestamoDAO = new PrestamoDAO();
    Prestamo prestamo = prestamoDAO.buscar(numeroControl);

    if (prestamo != null) {
        DefaultTableModel modelo = (DefaultTableModel) tabla_prestamos.getModel();
        modelo.setRowCount(0);
        Object[] fila = {
            prestamo.getId(),
            prestamo.getIdLibro(),
            prestamo.getNumeroControl(),
            prestamo.getFechaEntrega(),
            prestamo.getFechaSalida(),
            prestamo.getUnidades()
        };
        modelo.addRow(fila);
    } else {
        JOptionPane.showMessageDialog(null, "Préstamo no encontrado");
    }
         
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_IDPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDPrestamoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Informacion_Prestamo;
    private javax.swing.JPanel Prestamo_Panel;
    private javax.swing.JPanel Prestamo_Titulo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_buscarNumero;
    private javax.swing.JLabel label_fechaEntrega;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_libro;
    private javax.swing.JLabel label_numeroControl;
    private javax.swing.JLabel label_unidades;
    private javax.swing.JLabel lb_nombre1;
    private javax.swing.JTable tabla_prestamos;
    private javax.swing.JTextField txt_IDPrestamo;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_fechaEntrega;
    private javax.swing.JTextField txt_idLibro;
    private javax.swing.JTextField txt_numerocontrolPrestamo;
    private javax.swing.JTextField txt_unidades;
    // End of variables declaration//GEN-END:variables
}
