/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package intellibook;

import Models.Alumno;
import Models.AlumnoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JULI4
 */
public class Page_alumno extends javax.swing.JPanel {

 
    
    public Page_alumno() {
        initComponents();
    }
    
    
    //CODIGO PARA LIMPIAR PANTALLA
    
    public void limpiar(){
        txt_nombre.setText("");
        txt_correo.setText("");
        txt_numeroControl.setText("");
        txt_telefono.setText("");
        txt_carrera.setText("");
        txt_buscar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alumno_Panel = new javax.swing.JPanel();
        Alumno_Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_Informacion_Alumno = new javax.swing.JPanel();
        lb_buscarControl = new javax.swing.JLabel();
        lb_carrera = new javax.swing.JLabel();
        lb_correo = new javax.swing.JLabel();
        lb_numeroControl = new javax.swing.JLabel();
        lb_telefono = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_numeroControl = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        lb_nombre1 = new javax.swing.JLabel();
        lb_nombre2 = new javax.swing.JLabel();
        txt_carrera = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_alumnos = new javax.swing.JTable();

        Alumno_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Alumno_Titulo.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alumno");

        javax.swing.GroupLayout Alumno_TituloLayout = new javax.swing.GroupLayout(Alumno_Titulo);
        Alumno_Titulo.setLayout(Alumno_TituloLayout);
        Alumno_TituloLayout.setHorizontalGroup(
            Alumno_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Alumno_TituloLayout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        Alumno_TituloLayout.setVerticalGroup(
            Alumno_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alumno_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Alumno_Panel.add(Alumno_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Panel_Informacion_Alumno.setBackground(new java.awt.Color(51, 102, 255));

        lb_buscarControl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_buscarControl.setText("Numero de control:");

        lb_carrera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_carrera.setText("Carrera:");

        lb_correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_correo.setText("Correo electronico:");

        lb_numeroControl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_numeroControl.setText("Numero de control:");

        lb_telefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_telefono.setText("Telefono:");

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });

        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });

        btn_registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_consultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        lb_nombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_nombre1.setText("Nombre:");

        lb_nombre2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nombre2.setText("Buscar");

        txt_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_carreraActionPerformed(evt);
            }
        });

        tabla_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Correo", "N.Control", "Telefono", "Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_alumnos);

        javax.swing.GroupLayout Panel_Informacion_AlumnoLayout = new javax.swing.GroupLayout(Panel_Informacion_Alumno);
        Panel_Informacion_Alumno.setLayout(Panel_Informacion_AlumnoLayout);
        Panel_Informacion_AlumnoLayout.setHorizontalGroup(
            Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Informacion_AlumnoLayout.createSequentialGroup()
                                .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_numeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_numeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53))
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(lb_buscarControl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nombre2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Informacion_AlumnoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btn_registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_modificar)
                .addGap(24, 24, 24)
                .addComponent(btn_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_consultar)
                .addGap(42, 42, 42))
            .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lb_nombre1)
                    .addContainerGap(725, Short.MAX_VALUE)))
        );
        Panel_Informacion_AlumnoLayout.setVerticalGroup(
            Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                        .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Informacion_AlumnoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lb_nombre2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_buscarControl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(lb_correo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_numeroControl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_numeroControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_telefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_carrera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                .addGap(23, 23, 23)
                .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(Panel_Informacion_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_Informacion_AlumnoLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lb_nombre1)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );

        Alumno_Panel.add(Panel_Informacion_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alumno_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alumno_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    //CODIGO DE LOS BOTONES
    
    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // Codigo del boton para registrar alumnos
   String nombre = txt_nombre.getText();
   String correo = txt_correo.getText();
   String numeroControl = txt_numeroControl.getText();
   String telefono = txt_telefono.getText();
   String carrera = txt_carrera.getText();

    if (nombre.equals("") || correo.equals("") || numeroControl.equals("") || telefono.equals("") || carrera.equals("")) {
        JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
        
    } 
    else {
        Alumno alumno = new Alumno();
        alumno.setNombre(nombre);
        alumno.setCorreo(correo);
        alumno.setNumeroControl(numeroControl);
        alumno.setTelefono(telefono);
        alumno.setCarrera(carrera);

        AlumnoDAO alumnoDao = new AlumnoDAO();

        if (alumnoDao.registrar(alumno)) {
            JOptionPane.showMessageDialog(null, "Alumno registrado");
        } else {
            JOptionPane.showMessageDialog(null, "Error al registrar el alumno");
        }

        limpiar();
     
}
        
        
        
        
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed

    // Codigo del boton para modificar alumnos
    Alumno alumno = new Alumno();
    AlumnoDAO alumnodao = new AlumnoDAO();

    if (txt_buscar.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Ingrese el número de control");
    } else {
        String numeroControl = txt_numeroControl.getText();
        String nombre = txt_nombre.getText();
        String correo = txt_correo.getText();
        String telefono = txt_telefono.getText();
        String carrera = txt_carrera.getText();

        alumno.setNumeroControl(numeroControl);
        alumno.setNombre(nombre);
        alumno.setCorreo(correo);
        alumno.setTelefono(telefono);
        alumno.setCarrera(carrera);

        alumnodao.modificar(alumno);
        JOptionPane.showMessageDialog(null, "Registro modificado");
    }

    limpiar();


        
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // Boton de eliminar
         Alumno alumno = new Alumno();
        AlumnoDAO alumnodao = new AlumnoDAO();

         if(txt_buscar.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Ingrese el numero de control");
        }
        else{
            String numeroControl = txt_buscar.getText();
            alumno.setNumeroControl(numeroControl);
            JOptionPane.showMessageDialog(null, "Registro eliminado");

        }
        
     alumnodao.eliminar(txt_buscar.getText());
       
        limpiar();
        
 
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_carreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_carreraActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        // CODIGO DEL BOTON DE CONSULTA 
        AlumnoDAO alumnoDAO = new AlumnoDAO();
        DefaultTableModel modelo = alumnoDAO.consultar();
        tabla_alumnos.setModel(modelo);
        
        
        
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // CODIGO DEL BOTON BUSCAR 
        
        String numeroControl = txt_buscar.getText();
    AlumnoDAO alumnoDAO = new AlumnoDAO();
    Alumno alumno = alumnoDAO.buscar(numeroControl);

    if (alumno != null) {
        DefaultTableModel modelo = (DefaultTableModel) tabla_alumnos.getModel();
        modelo.setRowCount(0);
        Object[] fila = {
            alumno.getId(),
            alumno.getNombre(),
            alumno.getCorreo(),
            alumno.getNumeroControl(),
            alumno.getTelefono(),
            alumno.getCarrera()
        };
        modelo.addRow(fila);
    } else {
        JOptionPane.showMessageDialog(null, "Alumno no encontrado");
    }
        
    }//GEN-LAST:event_btn_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alumno_Panel;
    private javax.swing.JPanel Alumno_Titulo;
    private javax.swing.JPanel Panel_Informacion_Alumno;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_buscarControl;
    private javax.swing.JLabel lb_carrera;
    private javax.swing.JLabel lb_correo;
    private javax.swing.JLabel lb_nombre1;
    private javax.swing.JLabel lb_nombre2;
    private javax.swing.JLabel lb_numeroControl;
    private javax.swing.JLabel lb_telefono;
    private javax.swing.JTable tabla_alumnos;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_carrera;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numeroControl;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}




