
package intellibook;

import Models.Libro;
import Models.LibroDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JULI4
 */
public class Page_libro extends javax.swing.JPanel {

    /**
     * Creates new form Page_libro
     */
    public Page_libro() {
        initComponents();
    }
    
    public void limpiar(){
        txt_IDLibro.setText("");
        txt_buscar.setText("");
        txt_titulo.setText("");
        txt_unidades.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Libro_Panel = new javax.swing.JPanel();
        Libro_Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_Informacion_Libro = new javax.swing.JPanel();
        lb_Titulo = new javax.swing.JLabel();
        lb_cantidad = new javax.swing.JLabel();
        lb_IDlibro = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        txt_unidades = new javax.swing.JTextField();
        txt_IDLibro = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        lb_Titulo1 = new javax.swing.JLabel();
        lb_Titulo2 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_libros = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "N.Control", "N.Libros", "F. devolucion", "F. entrega"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(798, 510));

        Libro_Titulo.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Libro");

        javax.swing.GroupLayout Libro_TituloLayout = new javax.swing.GroupLayout(Libro_Titulo);
        Libro_Titulo.setLayout(Libro_TituloLayout);
        Libro_TituloLayout.setHorizontalGroup(
            Libro_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Libro_TituloLayout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        Libro_TituloLayout.setVerticalGroup(
            Libro_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Libro_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Panel_Informacion_Libro.setBackground(new java.awt.Color(51, 102, 255));
        Panel_Informacion_Libro.setPreferredSize(new java.awt.Dimension(800, 460));

        lb_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Titulo.setText("Titulo:");

        lb_cantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_cantidad.setText("Unidades:");

        lb_IDlibro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_IDlibro.setText("Libro ID:");

        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });

        txt_IDLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDLibroActionPerformed(evt);
            }
        });

        btn_registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_consultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        lb_Titulo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Titulo1.setText("ID Libro:");

        lb_Titulo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Titulo2.setText("Buscar");

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        tabla_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID ", "Titulo", "Unidades", "ID Libro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla_libros);

        javax.swing.GroupLayout Panel_Informacion_LibroLayout = new javax.swing.GroupLayout(Panel_Informacion_Libro);
        Panel_Informacion_Libro.setLayout(Panel_Informacion_LibroLayout);
        Panel_Informacion_LibroLayout.setHorizontalGroup(
            Panel_Informacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Informacion_LibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Informacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_IDlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Titulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(Panel_Informacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Informacion_LibroLayout.createSequentialGroup()
                        .addGroup(Panel_Informacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_Titulo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_Titulo1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(Panel_Informacion_LibroLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btn_registrar)
                .addGap(18, 18, 18)
                .addComponent(btn_modificar)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_consultar)
                .addGap(89, 89, 89))
        );
        Panel_Informacion_LibroLayout.setVerticalGroup(
            Panel_Informacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Informacion_LibroLayout.createSequentialGroup()
                .addGroup(Panel_Informacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Informacion_LibroLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(Panel_Informacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_buscar)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_Informacion_LibroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lb_Titulo)
                        .addGap(18, 18, 18)
                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_Informacion_LibroLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lb_Titulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_Titulo1)))
                .addGroup(Panel_Informacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Informacion_LibroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_cantidad)
                        .addGap(18, 18, 18)
                        .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_IDlibro)
                        .addGap(18, 18, 18)
                        .addComponent(txt_IDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Informacion_LibroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(Panel_Informacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout Libro_PanelLayout = new javax.swing.GroupLayout(Libro_Panel);
        Libro_Panel.setLayout(Libro_PanelLayout);
        Libro_PanelLayout.setHorizontalGroup(
            Libro_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Libro_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Panel_Informacion_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Libro_PanelLayout.setVerticalGroup(
            Libro_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Libro_PanelLayout.createSequentialGroup()
                .addComponent(Libro_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel_Informacion_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Libro_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Libro_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloActionPerformed

    private void txt_IDLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDLibroActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
         // Codigo del boton para registrar alumnos
     String titulo = txt_titulo.getText();
    String unidadesStr = txt_unidades.getText();
    String id_libro = txt_IDLibro.getText();

if (titulo.isEmpty() || unidadesStr.isEmpty() || id_libro.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Todos los campos son requeridos");
} else {
    int unidades = Integer.parseInt(unidadesStr);

    // El código restante para registrar el libro
    Libro libro = new Libro();
    libro.setTitulo(titulo);
    libro.setUnidades(unidades);
    libro.setId_libro(id_libro);

    LibroDAO librodao = new LibroDAO();

    if (librodao.registrar(libro)) {
        JOptionPane.showMessageDialog(null, "Libro registrado");
    } else {
        JOptionPane.showMessageDialog(null, "Error al registrar el libro");
    }

    limpiar();


    }//GEN-LAST:event_btn_registrarActionPerformed
    }
    
    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        // CODIGO DEL BOTON DE CONSULTA 
        LibroDAO librodao = new LibroDAO();
        DefaultTableModel modelo = librodao.consultar();
        tabla_libros.setModel(modelo);
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        
        // Botón de eliminar
    Libro libro = new Libro();
    LibroDAO librodao = new LibroDAO();

    String IDlibro = txt_buscar.getText();

    if (IDlibro.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese el ID del libro");
    } else {
        libro.setId_libro(IDlibro);
        if (librodao.eliminar(IDlibro)) {
            JOptionPane.showMessageDialog(null, "Registro eliminado");
        } 
    }
   
    limpiar();
        
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
         // Código del botón buscar
         String id_libro = txt_buscar.getText();
         LibroDAO librodao = new LibroDAO();
         Libro libro = librodao.buscar(id_libro);

    if (libro != null) {
        DefaultTableModel modelo = (DefaultTableModel) tabla_libros.getModel();
        modelo.setRowCount(0);
        Object[] fila = {
            libro.getTitulo(),
            libro.getUnidades(),
            libro.getId_libro()
        };
        modelo.addRow(fila);
    } else {
        JOptionPane.showMessageDialog(null, "Libro no encontrado");
    }
        
    
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // Codigo del boton para modificar alumnos
    Libro libro = new Libro();
    LibroDAO librodao = new LibroDAO();

    if (txt_buscar.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Ingrese el ID del libro");
    } else {
          String titulo = txt_titulo.getText();
          String unidadesStr = txt_unidades.getText();
          String id_libro = txt_IDLibro.getText();
   
          int unidades = Integer.parseInt(unidadesStr);

          libro.setId_libro(id_libro);
          libro.setUnidades(unidades);
          libro.setTitulo(titulo);

        librodao.modificar(libro);
        JOptionPane.showMessageDialog(null, "Libro modificado");
    }

    limpiar();


    }//GEN-LAST:event_btn_modificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Libro_Panel;
    private javax.swing.JPanel Libro_Titulo;
    private javax.swing.JPanel Panel_Informacion_Libro;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_IDlibro;
    private javax.swing.JLabel lb_Titulo;
    private javax.swing.JLabel lb_Titulo1;
    private javax.swing.JLabel lb_Titulo2;
    private javax.swing.JLabel lb_cantidad;
    private javax.swing.JTable tabla_libros;
    private javax.swing.JTextField txt_IDLibro;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_titulo;
    private javax.swing.JTextField txt_unidades;
    // End of variables declaration//GEN-END:variables
}
