/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package intellibook;

import Models.Devolucion;
import Models.DevolucionDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JULI4
 */
public class Page_devolucion extends javax.swing.JPanel {

    /**
     * Creates new form Page_devolucion
     */
    public Page_devolucion() {
        initComponents();
    }

    public void limpiar(){
        txt_IDPrestamo.setText("");
        txt_unidades.setText("");
        txt_IdLibro.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Devolucion_Panel = new javax.swing.JPanel();
        Devolucion_Titulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Informacion_Devolucion = new javax.swing.JPanel();
        lb_IDprestamo = new javax.swing.JLabel();
        txt_IDPrestamo = new javax.swing.JTextField();
        btn_devolver = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        txt_unidades = new javax.swing.JTextField();
        label_unidades = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_librosPrestados = new javax.swing.JTable();
        label_LibrosPrestados = new javax.swing.JLabel();
        label_IdLibro = new javax.swing.JLabel();
        txt_IdLibro = new javax.swing.JTextField();

        Devolucion_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Devolucion_Titulo.setBackground(new java.awt.Color(0, 51, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Devolucion");

        javax.swing.GroupLayout Devolucion_TituloLayout = new javax.swing.GroupLayout(Devolucion_Titulo);
        Devolucion_Titulo.setLayout(Devolucion_TituloLayout);
        Devolucion_TituloLayout.setHorizontalGroup(
            Devolucion_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Devolucion_TituloLayout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        Devolucion_TituloLayout.setVerticalGroup(
            Devolucion_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Devolucion_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Devolucion_Panel.add(Devolucion_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Panel_Informacion_Devolucion.setBackground(new java.awt.Color(51, 102, 255));

        lb_IDprestamo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_IDprestamo.setText("ID prestamo:");

        txt_IDPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IDPrestamoActionPerformed(evt);
            }
        });

        btn_devolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_devolver.setText("Devolver");
        btn_devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolverActionPerformed(evt);
            }
        });

        btn_consultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });

        txt_unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unidadesActionPerformed(evt);
            }
        });

        label_unidades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_unidades.setText("Unidades:");

        tabla_librosPrestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Prestamo", "ID Libro", "N.Control", "Unidades"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_librosPrestados);

        label_LibrosPrestados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_LibrosPrestados.setText("Libro prestados");

        label_IdLibro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_IdLibro.setText("ID Libro");

        txt_IdLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_Informacion_DevolucionLayout = new javax.swing.GroupLayout(Panel_Informacion_Devolucion);
        Panel_Informacion_Devolucion.setLayout(Panel_Informacion_DevolucionLayout);
        Panel_Informacion_DevolucionLayout.setHorizontalGroup(
            Panel_Informacion_DevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Informacion_DevolucionLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel_Informacion_DevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_devolver)
                    .addComponent(txt_IDPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_IDprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_IdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(Panel_Informacion_DevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_Informacion_DevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Informacion_DevolucionLayout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Informacion_DevolucionLayout.createSequentialGroup()
                            .addComponent(label_LibrosPrestados)
                            .addGap(225, 225, 225)))))
        );
        Panel_Informacion_DevolucionLayout.setVerticalGroup(
            Panel_Informacion_DevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Informacion_DevolucionLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(Panel_Informacion_DevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_IDprestamo)
                    .addComponent(label_LibrosPrestados))
                .addGap(13, 13, 13)
                .addGroup(Panel_Informacion_DevolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_Informacion_DevolucionLayout.createSequentialGroup()
                        .addComponent(txt_IDPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_unidades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_IdLibro)
                        .addGap(18, 18, 18)
                        .addComponent(txt_IdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btn_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        Devolucion_Panel.add(Panel_Informacion_Devolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 800, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Devolucion_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Devolucion_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_IDPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IDPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IDPrestamoActionPerformed

    private void txt_unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unidadesActionPerformed

    private void btn_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolverActionPerformed
        // BOTON DEVOLVER
        
        // Obtener los valores del formulario
    int idPrestamo = Integer.parseInt(txt_IDPrestamo.getText());
    int unidadesDevueltas = Integer.parseInt(txt_unidades.getText());
    String idLibro = txt_IdLibro.getText();

    // Crear una instancia de DevolucionDAO
    DevolucionDAO devolucionDAO = new DevolucionDAO();

    // Crear un objeto Devolucion y establecer los valores obtenidos
    Devolucion devolucion = new Devolucion();
    devolucion.setIDPrestamo(idPrestamo);
    devolucion.setUnidades(unidadesDevueltas);
    devolucion.setIdLibro(idLibro);

    // Llamar al método devolver de DevolucionDAO
    boolean devolucionExitosa = devolucionDAO.devolver(devolucion);

    if (devolucionExitosa) {
        JOptionPane.showMessageDialog(null, "Devolución exitosa. Las unidades devueltas se han sumado al libro.");
        limpiar();
    } else {
        JOptionPane.showMessageDialog(null, "Error al realizar la devolución. Por favor, inténtelo de nuevo.");
    }
       
        
        
        
    }//GEN-LAST:event_btn_devolverActionPerformed

    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        DevolucionDAO devoluciondao = new DevolucionDAO();

    DefaultTableModel modelo = devoluciondao.consultar();

    tabla_librosPrestados.setModel(modelo);
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void txt_IdLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdLibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Devolucion_Panel;
    private javax.swing.JPanel Devolucion_Titulo;
    private javax.swing.JPanel Panel_Informacion_Devolucion;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_devolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_IdLibro;
    private javax.swing.JLabel label_LibrosPrestados;
    private javax.swing.JLabel label_unidades;
    private javax.swing.JLabel lb_IDprestamo;
    private javax.swing.JTable tabla_librosPrestados;
    private javax.swing.JTextField txt_IDPrestamo;
    private javax.swing.JTextField txt_IdLibro;
    private javax.swing.JTextField txt_unidades;
    // End of variables declaration//GEN-END:variables
}
